### ISSUE TITLE
Improve training corpus by deleting some survey responses

### ISSUE THREAD

**Issue by DK1999** [18F/10x-MLaaS#46]
## 10x Qualitative Data User story 
As a Content Team Member, I want super accurate evaluations by HSM so that I don't miss any helpful comments or waste time reading unhelpful ones.

I suspect that survey responses in the training data could be made more helpful if we eliminated responses that originated on Contact Center-related pages. The pages tend to  have been flagged as unhelpful, but they might share words with helpful responses and thus throw off the learning. Meanwhile, we have stopped surveying from these pages. What other pages should we not include? I'll think about it.
  
## Acceptance criteria
- [ ] Contact Center pages removed from Training data
- [ ] Looked for similar pages to remove...
- [ ]

**Comment by csmcallister** [comment]
@DK1999 could you attach a list of the Contact Center-related pages (ideally in a spreadsheet)? I'd like to compare those comments to comments from the other urls. 

Specifically, I'd like to check for these two conditions:
 - Is there a *moderately* high degree of lexical similarity (calculated perhaps by a high [Jaccard similarity](https://en.wikipedia.org/wiki/Jaccard_index)) between the two groups of comments? Or could the Contact Center-related comments be lexically similar to future comments?
 - Would each of the Contact Center-related comments be classified the same way regardless of being a Contact Center-related comment?

If those conditions hold, the Contact Center-related comments might be making the classifier more discerning. That's because they're supplying instances of those edge cases, where a comment contains words that are normally hammy but, within a different context, are in fact spammy (or vice versa). Regardless, we can simulate model performance with and without those comments in the training data. So I'd suggest adding something like `Benchmark model performance with and without Contact Center-related pages` to the acceptance criteria. And then I'll run the tests and drop the results in here.

**Comment by TiffanyAndrews** [comment]
ARCHIVE
